<?php

// PHP WordPress category creation array for Tehran neighborhoods

/**
 * ایجاد دسته‌بندی‌های وردپرس برای محله‌های
 * برای اجرا این کد را در functions.php یا یک پلاگین قرار دهید
 * و سپس یک بار آدرس سایت را باز کنید
 */

$tehran_categories = [
    [
        'name' => 'منطقه ۱',
        'slug' => 'mintaqe-1',
        'children' => [
            ['name' => 'حصاربوعلی',           'slug' => 'hesar-boali'],
            ['name' => 'رستم‌آباد فرمانیه',   'slug' => 'rostam-abad-farmaniye'],
            ['name' => 'اوین',                 'slug' => 'evin'],
            ['name' => 'درکه',                 'slug' => 'darake'],
            ['name' => 'زعفرانیه',             'slug' => 'zafaraniye'],
            ['name' => 'محمودیه',              'slug' => 'mahmudiye'],
            ['name' => 'ولنجک',                'slug' => 'velenjak'],
            ['name' => 'امام‌زاده قاسم',       'slug' => 'emamzade-qasem'],
            ['name' => 'دربند',                'slug' => 'darband'],
            ['name' => 'گلابدره',              'slug' => 'golab-dare'],
            ['name' => 'جماران',               'slug' => 'jamaran'],
            ['name' => 'دزاشیب',               'slug' => 'dezashib'],
            ['name' => 'نیاوران',              'slug' => 'niavaran'],
            ['name' => 'اراج',                 'slug' => 'araj'],
            ['name' => 'کاشانک',               'slug' => 'kashanak'],
            ['name' => 'شهرک دانشگاه',         'slug' => 'shahrak-daneshgah'],
            ['name' => 'شهرک نفت',             'slug' => 'shahrak-naft'],
            ['name' => 'دارآباد',              'slug' => 'dar-abad'],
            ['name' => 'باغ فردوس',            'slug' => 'bagh-ferdos'],
            ['name' => 'تجریش',                'slug' => 'tajrish'],
            ['name' => 'قیطریه',               'slug' => 'qeytariye'],
            ['name' => 'چیذر',                 'slug' => 'chizar'],
            ['name' => 'حکمت',                 'slug' => 'hekmat'],
            ['name' => 'ازگل',                 'slug' => 'azgol'],
            ['name' => 'سوهانک',               'slug' => 'sohanak'],
            ['name' => 'شهید محلاتی',          'slug' => 'shahid-mahallati'],
            ['name' => 'اقدسیه',               'slug' => 'aqdassiye'],
            ['name' => 'الهیه – فرشته',        'slug' => 'elahiye-fereshte'],
            ['name' => 'اندرزگو',              'slug' => 'andarzgu'],
            ['name' => 'بلوار ارتش',           'slug' => 'bolvar-artesh'],
            ['name' => 'پارک‌وی',              'slug' => 'parkway'],
            ['name' => 'جمشیدیه',              'slug' => 'jamshidiye'],
            ['name' => 'دیباجی',               'slug' => 'dibaji'],
            ['name' => 'سعدآباد',              'slug' => 'saad-abad'],
            ['name' => 'صاحبقرانیه',           'slug' => 'saheb-qaraniye'],
            ['name' => 'فرمانیه',              'slug' => 'farmaniye'],
            ['name' => 'مقدس اردبیلی',         'slug' => 'moqaddas-ardabili'],
            ['name' => 'مینی سیتی',            'slug' => 'mini-city'],
            ['name' => 'نوبنیاد',              'slug' => 'nobonyad'],
            ['name' => 'ولیعصر',               'slug' => 'valiasr-1'],
            ['name' => 'کامرانیه',             'slug' => 'kamraniye'],
        ],
    ],
    [
        'name' => 'منطقه ۲',
        'slug' => 'mintaqe-2',
        'children' => [
            ['name' => 'بوعلی',                    'slug' => 'boali-2'],
            ['name' => 'سعادت‌آباد',               'slug' => 'saadat-abad'],
            ['name' => 'مدیریت',                   'slug' => 'modiriyat'],
            ['name' => 'کوهسار',                   'slug' => 'kuhsar-2'],
            ['name' => 'پونک',                     'slug' => 'punak-2'],
            ['name' => 'شهید چوب‌تراش',            'slug' => 'shahid-chob-tarash'],
            ['name' => 'شهید خرم‌رودی',            'slug' => 'shahid-kharam-rudi'],
            ['name' => 'صادقیه شمالی شهرک هما',   'slug' => 'sadeqiye-shomali-shahrak-homa'],
            ['name' => 'صادقیه',                   'slug' => 'sadeqiye'],
            ['name' => 'شهرآرا',                   'slug' => 'shahr-ara'],
            ['name' => 'کوی نصر',                  'slug' => 'kuy-nasr'],
            ['name' => 'پردیسان',                  'slug' => 'pardisan'],
            ['name' => 'شهرک آزمایش',              'slug' => 'shahrak-azmayesh'],
            ['name' => 'تهران‌ویلا',               'slug' => 'tehran-vila'],
            ['name' => 'برق آلستوم',               'slug' => 'barq-alestom'],
            ['name' => 'تیموری',                   'slug' => 'teymuri'],
            ['name' => 'طرشت',                     'slug' => 'tarasht'],
            ['name' => 'همایونشهر',                'slug' => 'homayun-shahr'],
            ['name' => 'توحید',                    'slug' => 'towhid-2'],
            ['name' => 'زنجان',                    'slug' => 'zanjan-2'],
            ['name' => 'شادمهر',                   'slug' => 'shadmehr'],
            ['name' => 'ایوانک',                   'slug' => 'ivanak'],
            ['name' => 'دریا',                     'slug' => 'darya'],
            ['name' => 'شهرک قدس',                 'slug' => 'shahrak-qods'],
            ['name' => 'آسمان‌ها',                 'slug' => 'asemanha'],
            ['name' => 'درختی',                    'slug' => 'deraakhti'],
            ['name' => 'فرحزاد',                   'slug' => 'farahzad'],
            ['name' => 'مخابرات',                  'slug' => 'mokhaberat'],
            ['name' => 'پرواز',                    'slug' => 'parvaz-2'],
            ['name' => 'آزادی',                    'slug' => 'azadi-2'],
            ['name' => 'بهبودی',                   'slug' => 'behbudi'],
            ['name' => 'جلال آل‌احمد',             'slug' => 'jalal-ale-ahmad'],
            ['name' => 'خوش شمالی',                'slug' => 'khosh-shomali'],
            ['name' => 'ستارخان',                  'slug' => 'satarkhan'],
            ['name' => 'شادمان',                   'slug' => 'shadman'],
            ['name' => 'شهرک ژاندارمری',           'slug' => 'shahrak-zhandarmeri'],
            ['name' => 'شهرک غرب',                 'slug' => 'shahrak-gharb'],
            ['name' => 'گیشا',                     'slug' => 'gisha'],
            ['name' => 'مترو شریف',                'slug' => 'metro-sharif'],
            ['name' => 'مرزداران',                 'slug' => 'marzdaran'],
        ],
    ],
    [
        'name' => 'منطقه ۳',
        'slug' => 'mintaqe-3',
        'children' => [
            ['name' => 'آرارات',                       'slug' => 'ararat'],
            ['name' => 'ونک',                          'slug' => 'vanak'],
            ['name' => 'امانیه',                       'slug' => 'amaniye'],
            ['name' => 'زرگنده',                       'slug' => 'zargande'],
            ['name' => 'درب دوم',                      'slug' => 'darbe-dovvom'],
            ['name' => 'رستم‌آباد و اختیاریه',        'slug' => 'rostam-abad-ekhtiariye'],
            ['name' => 'داودیه',                       'slug' => 'davudiye'],
            ['name' => 'سید خندان',                    'slug' => 'seyed-khandan'],
            ['name' => 'دروس',                         'slug' => 'darous'],
            ['name' => 'قبا',                          'slug' => 'qoba'],
            ['name' => 'قلهک',                         'slug' => 'qolhak'],
            ['name' => 'کاوسیه',                       'slug' => 'kavusiye'],
            ['name' => 'اختیاریه',                     'slug' => 'ekhtiariye'],
            ['name' => 'پاسداران',                     'slug' => 'pasdaran-3'],
            ['name' => 'جردن',                         'slug' => 'jordan'],
            ['name' => 'جلفا',                         'slug' => 'jolfa'],
            ['name' => 'خواجه‌عبدالله',               'slug' => 'khaje-abdollah'],
            ['name' => 'دولت (کلاهدوز)',               'slug' => 'dolat-kolahduze'],
            ['name' => 'شیخ بهایی',                    'slug' => 'sheikh-bahayi'],
            ['name' => 'شیراز',                        'slug' => 'shiraz-3'],
            ['name' => 'ظفر',                          'slug' => 'zafar'],
            ['name' => 'ملاصدرا',                      'slug' => 'mollasadra'],
            ['name' => 'میدان کتابی',                  'slug' => 'meydane-ketabi'],
            ['name' => 'میرداماد',                     'slug' => 'mirdamad'],
            ['name' => 'ولیعصر (بین پارک‌وی و نیایش)', 'slug' => 'valiasr-parkway-niyayesh'],
        ],
    ],
    [
        'name' => 'منطقه ۴',
        'slug' => 'mintaqe-4',
        'children' => [
            ['name' => 'مهران',                    'slug' => 'mehran-4'],
            ['name' => 'کاظم‌آباد',                'slug' => 'kazem-abad'],
            ['name' => 'کوهک',                     'slug' => 'kuhak'],
            ['name' => 'مجیدیه و شمس‌آباد',        'slug' => 'majidiye-shams-abad'],
            ['name' => 'پاسداران و ضرابخانه',       'slug' => 'pasdaran-zarrabkhane'],
            ['name' => 'حسین‌آباد و مبارک‌آباد',   'slug' => 'hoseyn-abad-mobarak-abad'],
            ['name' => 'شیان و لویزان',             'slug' => 'shiyan-lavisan'],
            ['name' => 'علم و صنعت',                'slug' => 'elm-va-sanat-4'],
            ['name' => 'نارمک',                    'slug' => 'narmak'],
            ['name' => 'تهرانپارس غربی',           'slug' => 'tehranpars-gharbi'],
            ['name' => 'جوادیه',                   'slug' => 'javadiye-4'],
            ['name' => 'خاک سفید',                 'slug' => 'khak-sefid'],
            ['name' => 'تهرانپارس شرقی',           'slug' => 'tehranpars-sharqi'],
            ['name' => 'قاسم‌آباد و ده نارمک',     'slug' => 'qasem-abad-deh-narmak'],
            ['name' => 'اوقاف',                    'slug' => 'owqaf'],
            ['name' => 'شمیران نو',                'slug' => 'shamiran-no'],
            ['name' => 'حکیمیه',                   'slug' => 'hakimiye'],
            ['name' => 'قنات کوثر',                'slug' => 'qanat-kowsar'],
            ['name' => 'کوهسار',                   'slug' => 'kuhsar-4'],
            ['name' => 'مجیدآباد',                 'slug' => 'majid-abad'],
            ['name' => 'بنی‌هاشم',                 'slug' => 'bani-hashem'],
            ['name' => 'پلیس',                     'slug' => 'polis'],
            ['name' => 'دلاوران',                  'slug' => 'delavaran'],
            ['name' => 'رسالت',                    'slug' => 'resalat-4'],
            ['name' => 'سراج',                     'slug' => 'sarraj'],
            ['name' => 'شمس‌آباد',                 'slug' => 'shams-abad-4'],
            ['name' => 'شهدا',                     'slug' => 'shohada-4'],
            ['name' => 'صیاد شیرازی',              'slug' => 'sayyad-shirazi'],
            ['name' => 'فرجام',                    'slug' => 'farjam'],
            ['name' => 'لویزان',                   'slug' => 'lavisan'],
            ['name' => 'میدان ملت',                'slug' => 'meydane-mellat'],
            ['name' => 'هروی',                     'slug' => 'heravi'],
            ['name' => 'هنگام',                    'slug' => 'hangam'],
        ],
    ],
    [
        'name' => 'منطقه ۵',
        'slug' => 'mintaqe-5',
        'children' => [
            ['name' => 'شهران جنوبی',              'slug' => 'shahran-jonubi'],
            ['name' => 'شهران شمالی',              'slug' => 'shahran-shomali'],
            ['name' => 'شهر زیبا',                 'slug' => 'shahr-ziba'],
            ['name' => 'اندیشه',                   'slug' => 'andishe-5'],
            ['name' => 'بهاران',                   'slug' => 'baharan-5'],
            ['name' => 'کن',                       'slug' => 'kan'],
            ['name' => 'المهدی',                   'slug' => 'almahdi'],
            ['name' => 'باغ فیض',                  'slug' => 'bagh-feyz'],
            ['name' => 'پونک جنوبی',               'slug' => 'punak-jonubi'],
            ['name' => 'پونک شمالی',               'slug' => 'punak-shomali'],
            ['name' => 'حصارک',                    'slug' => 'hesarak'],
            ['name' => 'شهرک نفت',                 'slug' => 'shahrak-naft-5'],
            ['name' => 'کوهسار',                   'slug' => 'kuhsar-5'],
            ['name' => 'مرادآباد',                 'slug' => 'morad-abad'],
            ['name' => 'پرواز',                    'slug' => 'parvaz-5'],
            ['name' => 'سازمان برنامه جنوبی',      'slug' => 'sazman-barname-jonubi'],
            ['name' => 'سازمان برنامه شمالی',      'slug' => 'sazman-barname-shomali'],
            ['name' => 'ارم',                      'slug' => 'eram'],
            ['name' => 'سازمان آب',                'slug' => 'sazman-ab'],
            ['name' => 'اباذر',                    'slug' => 'abazar-5'],
            ['name' => 'فردوس',                    'slug' => 'ferdos-5'],
            ['name' => 'مهران',                    'slug' => 'mehran-5'],
            ['name' => 'اکباتان',                  'slug' => 'ekbatan'],
            ['name' => 'بیمه',                     'slug' => 'bime'],
            ['name' => 'آپادانا',                  'slug' => 'apadana-5'],
            ['name' => 'جنت‌آباد جنوبی',           'slug' => 'jannat-abad-jonubi'],
            ['name' => 'جنت‌آباد شمالی',           'slug' => 'jannat-abad-shomali'],
            ['name' => 'جنت‌آباد مرکزی',           'slug' => 'jannat-abad-markazi'],
            ['name' => 'شاهین',                    'slug' => 'shahin-5'],
            ['name' => 'آیت‌الله کاشانی',          'slug' => 'ayatollah-kashani'],
            ['name' => 'اشرفی اصفهانی',            'slug' => 'ashrafi-esfahani'],
            ['name' => 'ایران‌زمین شمالی',         'slug' => 'iran-zamin-shomali'],
            ['name' => 'بلوار تعاون',              'slug' => 'bolvar-taavon'],
            ['name' => 'بلوار فردوس',              'slug' => 'bolvar-ferdos'],
            ['name' => 'بولیوار',                  'slug' => 'bolivar'],
            ['name' => 'پیامبر',                   'slug' => 'payambar'],
            ['name' => 'ستاری',                    'slug' => 'sattari'],
            ['name' => 'سردار جنگل',               'slug' => 'sardar-jangal'],
            ['name' => 'سولقان',                   'slug' => 'solaqan'],
            ['name' => 'شهید مهدی باکری',          'slug' => 'shahid-mahdi-bakeri'],
        ],
    ],
    [
        'name' => 'منطقه ۶',
        'slug' => 'mintaqe-6',
        'children' => [
            ['name' => 'نجات‌اللهی',               'slug' => 'nejatollahi'],
            ['name' => 'ایرانشهر',                 'slug' => 'iranshahr'],
            ['name' => 'پارک لاله',                'slug' => 'park-laleh'],
            ['name' => 'کشاورز غربی',              'slug' => 'keshavarz-gharbi'],
            ['name' => 'نصرت',                     'slug' => 'nosrat'],
            ['name' => '۱۶ آذر',                   'slug' => '16-azar'],
            ['name' => 'سنایی',                    'slug' => 'sanayi'],
            ['name' => 'بهجت‌آباد',                'slug' => 'behjat-abad'],
            ['name' => 'عباس‌آباد',                'slug' => 'abbas-abad-6'],
            ['name' => 'قزل‌قلعه',                 'slug' => 'qezel-qaleh'],
            ['name' => 'سیندخت',                   'slug' => 'sindokht'],
            ['name' => 'گل‌ها',                    'slug' => 'golha'],
            ['name' => 'شیراز جنوبی',              'slug' => 'shiraz-jonubi'],
            ['name' => 'گاندی',                    'slug' => 'gandhi'],
            ['name' => 'ساعی',                     'slug' => 'saei'],
            ['name' => 'یوسف‌آباد',                'slug' => 'yusof-abad'],
            ['name' => 'جهاد',                     'slug' => 'jehad'],
            ['name' => 'جنت',                      'slug' => 'jannat-6'],
            ['name' => 'آرژانتین',                 'slug' => 'argentina'],
            ['name' => 'اسکندری',                  'slug' => 'eskandari-6'],
            ['name' => 'امیرآباد',                 'slug' => 'amir-abad'],
            ['name' => 'بلوار کشاورز',             'slug' => 'bolvar-keshavarz'],
            ['name' => 'توانیر',                   'slug' => 'tavanir'],
            ['name' => 'جمال‌زاده',                'slug' => 'jamalzade-6'],
            ['name' => 'حافظ',                     'slug' => 'hafez-6'],
            ['name' => 'زرتشت',                    'slug' => 'zartosht'],
            ['name' => 'طالقانی',                  'slug' => 'taleqani'],
            ['name' => 'فاطمی',                    'slug' => 'fatemi'],
            ['name' => 'فلسطین',                   'slug' => 'felestine'],
            ['name' => 'میدان انقلاب اسلامی',      'slug' => 'meydane-enqelab'],
            ['name' => 'میدان ولیعصر',             'slug' => 'meydane-valiasr'],
            ['name' => 'وزراء',                    'slug' => 'vozara'],
            ['name' => 'کارگر شمالی',              'slug' => 'kargar-shomali'],
            ['name' => 'کردستان',                  'slug' => 'kordestan'],
            ['name' => 'کریم‌خان',                 'slug' => 'karimkhan'],
        ],
    ],
    [
        'name' => 'منطقه ۷',
        'slug' => 'mintaqe-7',
        'children' => [
            ['name' => 'شارق الف',                 'slug' => 'shareq-alef'],
            ['name' => 'دهقان',                    'slug' => 'dehqan-7'],
            ['name' => 'شارق ب',                   'slug' => 'shareq-be'],
            ['name' => 'گرگان',                    'slug' => 'gorgan-7'],
            ['name' => 'نظام‌آباد',                'slug' => 'nezam-abad'],
            ['name' => 'خواجه نصیر و حقوقی',       'slug' => 'khaje-nasir-hoqoqi'],
            ['name' => 'خواجه نظام شرقی',          'slug' => 'khaje-nezam-sharqi'],
            ['name' => 'خواجه نظام غربی',          'slug' => 'khaje-nezam-gharbi'],
            ['name' => 'کاج',                      'slug' => 'kaj'],
            ['name' => 'امجدیه خاقانی',             'slug' => 'amjadiye-khaqani'],
            ['name' => 'بهار',                     'slug' => 'bahar-7'],
            ['name' => 'سهروردی باغ صبا',          'slug' => 'sohrevardi-bagh-saba'],
            ['name' => 'شهید قندی – نیلوفر',       'slug' => 'shahid-qandi-niloofar'],
            ['name' => 'عباس‌آباد – اندیشه',       'slug' => 'abbas-abad-andishe-7'],
            ['name' => 'حشمتیه',                   'slug' => 'heshmatieh'],
            ['name' => 'دبستان',                   'slug' => 'dabostan'],
            ['name' => 'ارامنه الف',               'slug' => 'aramane-alef'],
            ['name' => 'ارامنه ب',                 'slug' => 'aramane-be'],
            ['name' => 'قصر',                      'slug' => 'qasr-7'],
            ['name' => 'آپادانا',                  'slug' => 'apadana-7'],
            ['name' => 'امام حسین',                'slug' => 'emam-hoseyn-7'],
            ['name' => 'انقلاب',                   'slug' => 'enqelab-7'],
            ['name' => 'خواجه نظام',               'slug' => 'khaje-nezam'],
            ['name' => 'سرباز',                    'slug' => 'sarbaz'],
            ['name' => 'سهروردی',                  'slug' => 'sohrevardi'],
            ['name' => 'شریعتی',                   'slug' => 'shariati-7'],
            ['name' => 'شهید مدنی',                'slug' => 'shahid-madani'],
            ['name' => 'شیخ صفی',                  'slug' => 'sheikh-safi'],
            ['name' => 'مدنی',                     'slug' => 'madani'],
            ['name' => 'مرودشت',                   'slug' => 'marvdasht'],
            ['name' => 'مطهری',                    'slug' => 'motahhari-7'],
            ['name' => 'مفتح جنوبی',               'slug' => 'mofateh-jonubi'],
            ['name' => 'هفت تیر',                  'slug' => 'haft-tir'],
        ],
    ],
    [
        'name' => 'منطقه ۸',
        'slug' => 'mintaqe-8',
        'children' => [
            ['name' => 'تهرانپارس',    'slug' => 'tehranpars-8'],
            ['name' => 'دردشت',        'slug' => 'dardosht'],
            ['name' => 'مدائن',        'slug' => 'madayen'],
            ['name' => 'هفت‌حوض',      'slug' => 'haft-howz'],
            ['name' => 'فدک',          'slug' => 'fadak'],
            ['name' => 'زرکش',         'slug' => 'zarkesh'],
            ['name' => 'نارمک',        'slug' => 'narmak-8'],
            ['name' => 'مجیدیه',       'slug' => 'majidiye-8'],
            ['name' => 'کرمان',        'slug' => 'kerman-8'],
            ['name' => 'لشگر شرقی',    'slug' => 'lashgar-sharqi'],
            ['name' => 'لشگر غربی',    'slug' => 'lashgar-gharbi'],
            ['name' => 'وحیدیه',       'slug' => 'vahidiye'],
            ['name' => 'تسلیحات',      'slug' => 'tasliyhat'],
            ['name' => 'جشنواره',      'slug' => 'jashnavare'],
            ['name' => 'سبلان',        'slug' => 'sabalan'],
        ],
    ],
    [
        'name' => 'منطقه ۹',
        'slug' => 'mintaqe-9',
        'children' => [
            ['name' => 'استاد معین',            'slug' => 'ostad-moein'],
            ['name' => 'دکتر هوشیار',           'slug' => 'doctor-hoshyar'],
            ['name' => 'شهید دستغیب',           'slug' => 'shahid-dastghaib'],
            ['name' => 'فتح',                   'slug' => 'fath-9'],
            ['name' => 'امامزاده عبدالله',      'slug' => 'emamzade-abdollah'],
            ['name' => 'شمشیری',                'slug' => 'shamshiri'],
            ['name' => 'سرآسیاب مهرآباد',       'slug' => 'sar-asiab-mehrabad'],
            ['name' => 'مهرآباد جنوبی',         'slug' => 'mehrabad-jonubi'],
            ['name' => 'سی‌متری جی',            'slug' => 'si-metri-ji'],
            ['name' => 'طوس',                   'slug' => 'tous'],
            ['name' => 'مهرآباد',               'slug' => 'mehrabad'],
            ['name' => 'فتح – صنعتی',           'slug' => 'fath-sanati'],
        ],
    ],
    [
        'name' => 'منطقه ۱۰',
        'slug' => 'mintaqe-10',
        'children' => [
            ['name' => 'بریانک',        'slug' => 'beryanak'],
            ['name' => 'سلیمانی تیموری', 'slug' => 'soleymani-teymuri'],
            ['name' => 'شبیری جی',      'slug' => 'shabiri-ji'],
            ['name' => 'هفت‌چنار',      'slug' => 'haft-chenar'],
            ['name' => 'سلسبیل جنوبی',  'slug' => 'selsabil-jonubi'],
            ['name' => 'کارون جنوبی',   'slug' => 'karun-jonubi'],
            ['name' => 'هاشمی',         'slug' => 'hashemi'],
            ['name' => 'زنجان جنوبی',   'slug' => 'zanjan-jonubi'],
            ['name' => 'سلسبیل شمالی',  'slug' => 'selsabil-shomali'],
            ['name' => 'کارون شمالی',   'slug' => 'karun-shomali'],
            ['name' => 'آذربایجان',     'slug' => 'azerbaijan-10'],
            ['name' => 'آزادی',         'slug' => 'azadi-10'],
            ['name' => 'امام خمینی',    'slug' => 'emam-khomeini-10'],
            ['name' => 'جیحون',         'slug' => 'jeyhun'],
            ['name' => 'حسام‌الدین',    'slug' => 'hesamoddin'],
            ['name' => 'خوش',           'slug' => 'khosh'],
            ['name' => 'دامپزشکی',      'slug' => 'dampezeshki'],
            ['name' => 'رودکی',         'slug' => 'rudaki'],
            ['name' => 'سینا',          'slug' => 'sina-10'],
            ['name' => 'قصرالدشت',      'slug' => 'qasroddasht'],
            ['name' => 'مالک اشتر',     'slug' => 'malek-ashtar'],
            ['name' => 'نواب',          'slug' => 'navvab'],
            ['name' => 'کارون',         'slug' => 'karun'],
            ['name' => 'کمیل',          'slug' => 'komeil'],
        ],
    ],
    [
        'name' => 'منطقه ۱۱',
        'slug' => 'mintaqe-11',
        'children' => [
            ['name' => 'شیخ هادی',                 'slug' => 'sheikh-hadi'],
            ['name' => 'انقلاب',                   'slug' => 'enqelab-11'],
            ['name' => 'امیریه (فرهنگ)',            'slug' => 'amiriye-farhang'],
            ['name' => 'فروزش',                    'slug' => 'foruzesh'],
            ['name' => 'قلمستان',                  'slug' => 'qalamestan'],
            ['name' => 'منیریه',                   'slug' => 'moniriye'],
            ['name' => 'حشمت‌الدوله – جمال‌زاده',  'slug' => 'heshmatodowle-jamalzade'],
            ['name' => 'اسکندری',                  'slug' => 'eskandari-11'],
            ['name' => 'دخانیات',                  'slug' => 'dokhaniyat'],
            ['name' => 'مخصوص',                    'slug' => 'makhsus'],
            ['name' => 'جمهوری',                   'slug' => 'jomhuri'],
            ['name' => 'حر',                       'slug' => 'horr'],
            ['name' => 'انبار نفت',                'slug' => 'anbar-naft'],
            ['name' => 'آگاهی',                    'slug' => 'agahi'],
            ['name' => 'راه‌آهن',                  'slug' => 'raah-ahan-11'],
            ['name' => 'عباسی',                    'slug' => 'abbasi-11'],
            ['name' => 'هلال احمر',                'slug' => 'helal-ahmar-11'],
            ['name' => 'ابوسعید',                  'slug' => 'abosaeid'],
            ['name' => 'اسکندری جنوبی',            'slug' => 'eskandari-jonubi'],
            ['name' => 'پاستور',                   'slug' => 'pastor'],
            ['name' => 'حسن‌آباد',                 'slug' => 'hasan-abad'],
            ['name' => 'گمرک',                     'slug' => 'gomrok'],
            ['name' => 'وحدت اسلامی',              'slug' => 'vahdat-eslami'],
            ['name' => 'ولیعصر',                   'slug' => 'valiasr-11'],
            ['name' => 'کارگر جنوبی',              'slug' => 'kargar-jonubi'],
            ['name' => 'کاشان',                    'slug' => 'kashan-11'],
        ],
    ],
    [
        'name' => 'منطقه ۱۲',
        'slug' => 'mintaqe-12',
        'children' => [
            ['name' => 'بهارستان',         'slug' => 'baharestan-12'],
            ['name' => 'فردوسی',           'slug' => 'ferdowsi'],
            ['name' => 'امامزاده یحیی',    'slug' => 'emamzade-yahya'],
            ['name' => 'پامنار',           'slug' => 'pamnar'],
            ['name' => 'بازار',            'slug' => 'bazar'],
            ['name' => 'سنگلج',            'slug' => 'sangalaj'],
            ['name' => 'تختی',             'slug' => 'takhti-12'],
            ['name' => 'هرندی',            'slug' => 'harandi'],
            ['name' => 'آبشار',            'slug' => 'abshar-12'],
            ['name' => 'قیام',             'slug' => 'qiyam-12'],
            ['name' => 'کوثر',             'slug' => 'kowsar-12'],
            ['name' => 'ایران',            'slug' => 'iran-12'],
            ['name' => 'دروازه شمیران',    'slug' => 'darvaze-shamiran'],
            ['name' => 'امین‌حضور',        'slug' => 'amin-hozur'],
            ['name' => 'پانزده خرداد',     'slug' => 'panzda-khordad'],
            ['name' => 'پیچ شمیران',       'slug' => 'pich-shamiran'],
            ['name' => 'خراسان',           'slug' => 'khorasan-12'],
            ['name' => 'ری',               'slug' => 'rey-12'],
            ['name' => 'سعدی',             'slug' => 'saadi'],
            ['name' => 'لاله‌زار نو',      'slug' => 'lalezar-no'],
            ['name' => 'مولوی',            'slug' => 'molavi'],
            ['name' => 'میدان قیام',       'slug' => 'meydane-qiyam'],
        ],
    ],
    [
        'name' => 'منطقه ۱۳',
        'slug' => 'mintaqe-13',
        'children' => [
            ['name' => 'صفا',              'slug' => 'safa-13'],
            ['name' => 'شهید اسدی',        'slug' => 'shahid-asadi'],
            ['name' => 'زاهد گیلانی',      'slug' => 'zahed-gilani'],
            ['name' => 'اشراقی',           'slug' => 'eshraqi'],
            ['name' => 'دهقان',            'slug' => 'dehqan-13'],
            ['name' => 'نیروی هوایی',      'slug' => 'niru-havaeyi'],
            ['name' => 'پیروزی',           'slug' => 'pirouzi'],
            ['name' => 'حافظیه',           'slug' => 'hafeziye'],
            ['name' => 'امامت',            'slug' => 'emamat'],
            ['name' => 'شورا',             'slug' => 'shura'],
            ['name' => 'آشتیانی',          'slug' => 'ashtiyani'],
            ['name' => 'زینبیه',           'slug' => 'zeynabiye'],
            ['name' => 'سرخه‌حصار',        'slug' => 'sorkhe-hesar'],
            ['name' => 'تهران نو',          'slug' => 'tehran-no'],
            ['name' => 'دماوند',           'slug' => 'damavand-13'],
        ],
    ],
    [
        'name' => 'منطقه ۱۴',
        'slug' => 'mintaqe-14',
        'children' => [
            ['name' => 'شکوفه',            'slug' => 'shokufe-14'],
            ['name' => 'چهارصد دستگاه',    'slug' => 'chahar-sad-dastgah'],
            ['name' => 'جابری',            'slug' => 'jaberi'],
            ['name' => 'دژکام',            'slug' => 'dezhkam'],
            ['name' => 'شاهین',            'slug' => 'shahin-14'],
            ['name' => 'مینای شمالی',      'slug' => 'mina-shomali'],
            ['name' => 'نیکنام',           'slug' => 'niknam'],
            ['name' => 'آهنگران',          'slug' => 'ahangaran'],
            ['name' => 'بروجردی',          'slug' => 'borujedi'],
            ['name' => 'صد دستگاه',        'slug' => 'sad-dastgah'],
            ['name' => 'فرزانه',           'slug' => 'farzane'],
            ['name' => 'سر آسیاب دولاب',   'slug' => 'sar-asiab-dolab'],
            ['name' => 'شیوا',             'slug' => 'shiva'],
            ['name' => 'نبی اکرم (ص)',      'slug' => 'nabi-akram'],
            ['name' => 'شهرابی (قیام)',     'slug' => 'shahrabi-qiyam'],
            ['name' => 'شکیب',             'slug' => 'shakib'],
            ['name' => 'پرستار',           'slug' => 'parastar'],
            ['name' => 'سیزده آبان',       'slug' => 'sizdah-aban'],
            ['name' => 'ابوذر',            'slug' => 'abuzar-14'],
            ['name' => 'تاکسیرانی',        'slug' => 'taksrani'],
            ['name' => 'مینای جنوبی',      'slug' => 'mina-jonubi'],
            ['name' => 'دولاب',            'slug' => 'dolab'],
            ['name' => 'خاوران',           'slug' => 'khavaran-14'],
            ['name' => 'آهنگ شرقی',        'slug' => 'ahang-sharqi'],
            ['name' => 'آهنگ',             'slug' => 'ahang-14'],
            ['name' => 'قصر فیروزه',       'slug' => 'qasr-firuze'],
            ['name' => 'افراسیابی شمالی',  'slug' => 'afrasiabi-shomali'],
            ['name' => 'پاسدار گمنام',     'slug' => 'pasdar-gomnam'],
            ['name' => 'فلاح',             'slug' => 'fallah'],
            ['name' => 'نبرد',             'slug' => 'nabard'],
            ['name' => 'هفده شهریور',      'slug' => 'hevda-shahrivar-14'],
        ],
    ],
    [
        'name' => 'منطقه ۱۵',
        'slug' => 'mintaqe-15',
        'children' => [
            ['name' => 'مظاهری',           'slug' => 'mazaheri'],
            ['name' => 'مینابی',           'slug' => 'minabi'],
            ['name' => 'بیسیم',            'slug' => 'bisim'],
            ['name' => 'شوش',              'slug' => 'shush'],
            ['name' => 'طیب',              'slug' => 'tayeb'],
            ['name' => 'مطهری',            'slug' => 'motahhari-15'],
            ['name' => 'ابوذر',            'slug' => 'abuzar-15'],
            ['name' => 'هاشم‌آباد',        'slug' => 'hashem-abad'],
            ['name' => 'اتابک',            'slug' => 'atabak'],
            ['name' => 'شهید بروجردی',     'slug' => 'shahid-borujedi'],
            ['name' => 'کیانشهر شمالی',    'slug' => 'kiyanshahr-shomali'],
            ['name' => 'کیانشهر جنوبی',    'slug' => 'kiyanshahr-jonubi'],
            ['name' => 'رضویه',            'slug' => 'razaviye'],
            ['name' => 'مشیریه',           'slug' => 'mashiriye-15'],
            ['name' => 'افسریه شمالی',     'slug' => 'afsariye-shomali'],
            ['name' => 'افسریه جنوبی',     'slug' => 'afsariye-jonubi'],
            ['name' => 'مسعودیه',          'slug' => 'masudiye'],
            ['name' => 'والفجر',           'slug' => 'valfajr'],
            ['name' => 'قیامدشت',          'slug' => 'qiyamdosht'],
            ['name' => 'خاورشهر',          'slug' => 'khavar-shahr'],
            ['name' => 'آهنگ',             'slug' => 'ahang-15'],
            ['name' => 'افسریه',           'slug' => 'afsariye'],
            ['name' => 'خاوران',           'slug' => 'khavaran-15'],
            ['name' => 'مشیریه',           'slug' => 'mashiriye'],
        ],
    ],
    [
        'name' => 'منطقه ۱۶',
        'slug' => 'mintaqe-16',
        'children' => [
            ['name' => 'جوادیه',                       'slug' => 'javadiye-16'],
            ['name' => 'نازی‌آباد',                    'slug' => 'nazi-abad'],
            ['name' => 'خزانه',                        'slug' => 'khazane'],
            ['name' => 'شهرک بعثت',                    'slug' => 'shahrak-besat'],
            ['name' => 'علی‌آباد شمالی',               'slug' => 'ali-abad-shomali'],
            ['name' => 'یاخچی‌آباد و چهارصد دستگاه',  'slug' => 'yakhchi-abad-chaharsad-dastgah'],
            ['name' => 'تختی',                         'slug' => 'takhti-16'],
            ['name' => 'علی‌آباد جنوبی',               'slug' => 'ali-abad-jonubi'],
            ['name' => 'باغ آذری',                     'slug' => 'bagh-azari'],
            ['name' => 'راه‌آهن',                      'slug' => 'raah-ahan-16'],
            ['name' => 'رجایی',                        'slug' => 'rajayi-16'],
            ['name' => 'هلال احمر',                    'slug' => 'helal-ahmar-16'],
            ['name' => 'یاخچی‌آباد',                   'slug' => 'yakhchi-abad'],
        ],
    ],
    [
        'name' => 'منطقه ۱۷',
        'slug' => 'mintaqe-17',
        'children' => [
            ['name' => 'ابوذر غربی',           'slug' => 'abuzar-gharbi'],
            ['name' => 'آذری',                 'slug' => 'azari'],
            ['name' => 'امامزاده حسن (ع)',      'slug' => 'emamzade-hasan'],
            ['name' => 'یافت‌آباد',            'slug' => 'yaft-abad-17'],
            ['name' => 'جلیلی',                'slug' => 'jalili'],
            ['name' => 'زهتابی',               'slug' => 'zehtabi'],
            ['name' => 'زمزم',                 'slug' => 'zamzam'],
            ['name' => 'سجاد',                 'slug' => 'sajjad-17'],
            ['name' => 'گلچین',                'slug' => 'golchin'],
            ['name' => 'وصفنارد',              'slug' => 'vasfnard'],
            ['name' => 'ابوذر شرقی',           'slug' => 'abuzar-sharqi'],
            ['name' => 'باغ خزانه',            'slug' => 'bagh-khazane'],
            ['name' => 'بلورسازی',             'slug' => 'bolursazi'],
            ['name' => 'مقدم',                 'slug' => 'moqaddam'],
            ['name' => 'قزوین',                'slug' => 'qazvin-17'],
            ['name' => 'قلعه مرغی',            'slug' => 'qaleh-morghi'],
            ['name' => 'میدان بهاران',          'slug' => 'meydane-baharan'],
        ],
    ],
    [
        'name' => 'منطقه ۱۸',
        'slug' => 'mintaqe-18',
        'children' => [
            ['name' => 'فردوس',                    'slug' => 'ferdos-18'],
            ['name' => 'تولیدارو',                 'slug' => 'tulidaro'],
            ['name' => 'بهداشت',                   'slug' => 'behdashte-18'],
            ['name' => 'ولیعصر شمالی',             'slug' => 'valiasr-shomali-18'],
            ['name' => 'رجائی',                    'slug' => 'rajayi-18'],
            ['name' => 'ولیعصر جنوبی',             'slug' => 'valiasr-jonubi-18'],
            ['name' => 'صادقیه',                   'slug' => 'sadeqiye-18'],
            ['name' => 'صاحب‌الزمان',              'slug' => 'sahebozzaman'],
            ['name' => 'یافت‌آباد جنوبی',          'slug' => 'yaft-abad-jonubi'],
            ['name' => 'یافت‌آباد شمالی',          'slug' => 'yaft-abad-shomali'],
            ['name' => 'شادآباد',                  'slug' => 'shad-abad'],
            ['name' => 'هفده شهریور',              'slug' => 'hevda-shahrivar-18'],
            ['name' => 'امام خمینی (ره)',           'slug' => 'emam-khomeini-18'],
            ['name' => 'شمس‌آباد',                 'slug' => 'shams-abad-18'],
            ['name' => 'خلیج فارس شمالی',          'slug' => 'khalij-fars-shomali'],
            ['name' => 'خلیج فارس جنوبی',          'slug' => 'khalij-fars-jonubi'],
            ['name' => 'خلیج فارس',                'slug' => 'khalij-fars'],
            ['name' => 'سعیدآباد',                 'slug' => 'saeid-abad'],
            ['name' => 'شهرک صاحب‌الزمان',         'slug' => 'shahrak-sahebozzaman'],
            ['name' => 'شهرک ولیعصر',              'slug' => 'shahrak-valiasr'],
        ],
    ],
    [
        'name' => 'منطقه ۱۹',
        'slug' => 'mintaqe-19',
        'children' => [
            ['name' => 'خانی‌آباد نو شمالی',      'slug' => 'khani-abad-no-shomali'],
            ['name' => 'اسفندیاری و بستان',        'slug' => 'esfandiyari-bostan'],
            ['name' => 'بهمنیار',                  'slug' => 'bahmanyar'],
            ['name' => 'خانی‌آباد نو جنوبی',       'slug' => 'khani-abad-no-jonubi'],
            ['name' => 'شریعتی جنوبی',             'slug' => 'shariati-jonubi'],
            ['name' => 'شریعتی شمالی',             'slug' => 'shariati-shomali'],
            ['name' => 'شکوفه جنوبی',              'slug' => 'shokufe-jonubi'],
            ['name' => 'شکوفه شمالی',              'slug' => 'shokufe-shomali'],
            ['name' => 'نعمت‌آباد',                'slug' => 'nemat-abad'],
            ['name' => 'دولت‌خواه',                'slug' => 'dolat-khah'],
            ['name' => 'اسماعیل‌آباد',             'slug' => 'esmail-abad'],
            ['name' => 'شهید کاظمی',               'slug' => 'shahid-kazemi'],
            ['name' => 'رسالت',                    'slug' => 'resalat-19'],
            ['name' => 'خانی‌آباد نو',             'slug' => 'khani-abad-no'],
            ['name' => 'عبدل‌آباد',                'slug' => 'abdol-abad'],
        ],
    ],
    [
        'name' => 'منطقه ۲۰',
        'slug' => 'mintaqe-20',
        'children' => [
            ['name' => 'اقدسیه',        'slug' => 'aqdassiye-20'],
            ['name' => 'صفائیه',        'slug' => 'safaeiye'],
            ['name' => 'ظهیرآباد',      'slug' => 'zahir-abad'],
            ['name' => 'غیوری',         'slug' => 'gheyuri'],
            ['name' => 'جوانمرد',       'slug' => 'javanmard'],
            ['name' => 'حمزه‌آباد',     'slug' => 'hamze-abad'],
            ['name' => 'دیلمان',        'slug' => 'deylaman'],
            ['name' => 'فیروزآبادی',    'slug' => 'firuz-abadi'],
            ['name' => 'منصوریه',       'slug' => 'mansuriye'],
            ['name' => '۱۳ آبان',       'slug' => '13-aban'],
            ['name' => 'دولت‌آباد',     'slug' => 'dolat-abad-20'],
            ['name' => 'شهادت',         'slug' => 'shahadat'],
            ['name' => 'استخر',         'slug' => 'estakhr'],
            ['name' => 'بهشتی',         'slug' => 'beheshti-20'],
            ['name' => 'سرتخت',         'slug' => 'sartakht'],
            ['name' => 'علائین',        'slug' => 'alayin'],
            ['name' => 'نفرآباد',       'slug' => 'nafar-abad'],
            ['name' => 'ولی‌آباد',      'slug' => 'vali-abad'],
            ['name' => 'امین‌آباد',     'slug' => 'amin-abad-20'],
            ['name' => 'تقی‌آباد',      'slug' => 'taqi-abad'],
            ['name' => 'نظامی',         'slug' => 'nezami-20'],
            ['name' => 'عباس‌آباد',     'slug' => 'abbas-abad-20'],
            ['name' => 'کهریزک',        'slug' => 'kahrizak'],
        ],
    ],
    [
        'name' => 'منطقه ۲۱',
        'slug' => 'mintaqe-21',
        'children' => [
            ['name' => 'شهرک دریا',                'slug' => 'shahrak-darya'],
            ['name' => 'تهرانسر غربی',             'slug' => 'tehransar-gharbi'],
            ['name' => 'تهرانسر شرقی',             'slug' => 'tehransar-sharqi'],
            ['name' => 'باشگاه نفت',               'slug' => 'bashgah-naft'],
            ['name' => 'تهرانسر مرکزی',            'slug' => 'tehransar-markazi'],
            ['name' => 'شهرک پاسداران',            'slug' => 'shahrak-pasdaran'],
            ['name' => 'تهرانسر شمالی',            'slug' => 'tehransar-shomali'],
            ['name' => 'شهرک آزادی',               'slug' => 'shahrak-azadi'],
            ['name' => 'شهرک فرهنگیان',            'slug' => 'shahrak-farhangian'],
            ['name' => 'شهرک استقلال',             'slug' => 'shahrak-esteqlal'],
            ['name' => 'شهرک دانشگاه',             'slug' => 'shahrak-daneshgah-21'],
            ['name' => 'چیتگر شمالی',              'slug' => 'chitgar-shomali'],
            ['name' => 'چیتگر جنوبی (شهرک ۲۲ بهمن)', 'slug' => 'chitgar-jonubi-22-bahman'],
            ['name' => 'ویلا شهر',                 'slug' => 'vila-shahr'],
            ['name' => 'وردآورد',                  'slug' => 'vardavard'],
            ['name' => 'شهرک غزالی',               'slug' => 'shahrak-ghazali'],
            ['name' => 'شهرک شهرداری',             'slug' => 'shahrak-shahrdari'],
            ['name' => 'تهرانسر',                  'slug' => 'tehransar'],
            ['name' => 'شهرک ۲۲ بهمن',             'slug' => 'shahrak-22-bahman'],
            ['name' => 'شهرک دانشگاه شریف',        'slug' => 'shahrak-daneshgah-sharif'],
        ],
    ],
    [
        'name' => 'منطقه ۲۲',
        'slug' => 'mintaqe-22',
        'children' => [
            ['name' => 'دهکده المپیک',                     'slug' => 'dehkade-olampik'],
            ['name' => 'زیبادشت بالا',                     'slug' => 'ziba-dasht-bala'],
            ['name' => 'گلستان شرقی',                      'slug' => 'golestan-sharqi'],
            ['name' => 'زیبادشت پایین',                    'slug' => 'ziba-dasht-payin'],
            ['name' => 'شریف',                             'slug' => 'sharif-22'],
            ['name' => 'گلستان غربی',                      'slug' => 'golestan-gharbi'],
            ['name' => 'امید – دژبان',                     'slug' => 'omid-dezhban'],
            ['name' => 'شهید باقری',                       'slug' => 'shahid-baqeri'],
            ['name' => 'آزادشهر',                          'slug' => 'azad-shahr'],
            ['name' => 'پیکان‌شهر',                        'slug' => 'peykan-shahr'],
            ['name' => 'دریاچه چیتگر',                     'slug' => 'daryache-chitgar'],
            ['name' => 'شهرک راه‌آهن – شهرک گلستان',      'slug' => 'shahrak-raah-ahan-golestan'],
        ],
    ],
];


/**
 * تابع ایجاد دسته‌بندی‌ها در وردپرس
 * taxonomy: پیش‌فرض 'category' است، می‌توانید 'product_cat' برای ووکامرس یا هر تاکسونومی دیگری بگذارید
 */
function create_tehran_categories($taxonomy = 'category')
{
    global $tehran_categories;

    foreach ($tehran_categories as $region) {
        // ایجاد دسته‌بندی والد (منطقه)
        $parent_term = term_exists($region['slug'], $taxonomy);

        if (! $parent_term) {
            $parent_term = wp_insert_term(
                $region['name'],
                $taxonomy,
                ['slug' => $region['slug']]
            );
        }

        if (is_wp_error($parent_term)) {
            continue;
        }

        $parent_id = is_array($parent_term) ? $parent_term['term_id'] : $parent_term;

        // ایجاد دسته‌بندی‌های فرزند (محله‌ها)
        foreach ($region['children'] as $child) {
            if (! term_exists($child['slug'], $taxonomy)) {
                wp_insert_term(
                    $child['name'],
                    $taxonomy,
                    [
                        'slug'   => $child['slug'],
                        'parent' => $parent_id,
                    ]
                );
            }
        }
    }
}

// اجرای یک‌باره هنگام لود سایت — پس از اجرا این خط را حذف کنید
add_action('init', function () {
    if (get_option('tehran_categories_created')) return;
    create_tehran_categories('category'); // یا 'product_cat' برای ووکامرس
    update_option('tehran_categories_created', true);
});
